# Configuration par défaut de Podcasteur
# Optimisée pour les podcasts en français

# ========================================
# PARAMÈTRES AUDIO
# ========================================
audio:
  format_export: "mp3"        # Format de sortie : mp3, wav, ogg
  debit: "192k"               # Bitrate MP3 : 128k, 192k, 256k, 320k
  duree_fondu: 100            # Durée des fondus en ms (entrée/sortie)
  silence_entre_segments: 500 # Silence entre segments en ms
  normaliser: true            # Normaliser le volume

# ========================================
# TRANSCRIPTION (WhisperX)
# ========================================
transcription:
  modele: "base"              # Modèles WhisperX pour français :
                              # - tiny   : ~40s/min, moins précis (léger)
                              # - base   : ~1min/min, bon compromis (recommandé)
                              # - small  : ~2min/min, très précis
                              # - medium : ~4min/min, excellent (GPU recommandé)
                              # - large-v2 : ~8min/min, meilleur (GPU nécessaire)

  langue: "fr"                # Toujours français
  dossier_sortie: "transcriptions"

# ========================================
# ANALYSE IA (Claude)
# ========================================
analyse_ia:
  modele: "claude-sonnet-4-5-20250929"  # Modèle Claude à utiliser
  duree_cible: 5              # Durée cible du podcast en minutes
  ton: "informatif et dynamique"  # Ton souhaité pour les suggestions
                              # Options suggérées:
                              # - "informatif et dynamique"
                              # - "détendu et conversationnel"
                              # - "professionnel et concis"
                              # - "créatif et narratif"
  nombre_suggestions: 3       # Nombre de suggestions à générer
  temperature: 0.7            # Créativité de Claude (0.0 = précis, 1.0 = créatif)

# ========================================
# TRI DES FICHIERS
# ========================================
tri_fichiers:
  methode: "nom"              # Méthode de tri : "nom" ou "date"
  ordre: "asc"                # Ordre : "asc" (croissant) ou "desc" (décroissant)

# ========================================
# VALIDATION
# ========================================
validation:
  verifier_timestamps: true   # Vérifier que les timestamps sont valides
  tolerance_timestamps: 0.5   # Tolérance en secondes pour les dépassements


elements_sonores:
  activer: true
  generique_debut:
    fichier: "assets/intro.wav"
    duree_fondu_sortie: 1  # ms
  generique_fin:
    fichier: "assets/outro.wav"
    duree_fondu_entree: 1
  virgule_sonore:
    fichier: "assets/jingle.mp3"
    position: "desactive"  # ou "entre_segments"
    duree_fondu_entree: 500
    duree_fondu_sortie: 500