name: Build GUI Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install FFmpeg
        run: |
          choco install ffmpeg -y

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall pathlib -y
          pip install -r requirements.txt
          pip install pyinstaller pyinstaller-hooks-contrib

      - name: Build executable
        run: |
          pyinstaller podcasteur_gui.spec

      - name: Create distribution package
        shell: bash
        run: |
          # Détecter la version correctement
          if [[ "${{ github.event_name }}" == "push" ]] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            version="${GITHUB_REF_NAME#v}"
          else
            version="manual-$(date +%Y%m%d-%H%M%S)"
          fi
          
          echo "Version détectée: $version"
          dist_name="Podcasteur-GUI-Windows-${version}"
          
          mkdir -p "${dist_name}"
          cp dist/Podcasteur.exe "${dist_name}/"
          cp .env.example "${dist_name}/.env.example"
          cp README_WINDOWS.txt "${dist_name}/README.txt"
          cp RELEASE_NOTES.md "${dist_name}/NOTES_VERSION.md"
          
          # README d'installation
          cat > "${dist_name}/README.txt" << 'EOF'
          ================================================
          Podcasteur GUI v${version} - Windows
          ================================================
          
          INSTALLATION RAPIDE:
          
          1. Créez un fichier .env dans ce dossier
             (copiez .env.example et renommez en .env)
             
          2. Éditez .env avec un éditeur de texte :
             ANTHROPIC_API_KEY=sk-ant-xxxxx
             
          3. Double-cliquez sur Podcasteur.exe
          
          IMPORTANT : Le fichier .env DOIT être dans le même
          dossier que Podcasteur.exe
          
          PRÉREQUIS:
          - FFmpeg doit être installé et dans le PATH
          - Windows 10/11
          
          SUPPORT:
          https://github.com/lebidul/podcasteur
          EOF
          
          # Créer l'archive ZIP
          7z a "${dist_name}.zip" "${dist_name}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: podcasteur-gui-windows
          path: Podcasteur-GUI-Windows-*.zip

      - name: Create Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          files: Podcasteur-GUI-Windows-*.zip
          draft: false
          prerelease: false
